# Generated by Django 3.1.3 on 2021-01-02 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentitems',
            name='item_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rentitems',
            name='rented_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 20, 51, 59, 534857)),
        ),
    ]
