# Generated by Django 3.1.3 on 2021-01-02 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_auto_20210102_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentitems',
            name='item_collected',
        ),
        migrations.AlterField(
            model_name='rentitems',
            name='rented_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 21, 26, 58, 101835)),
        ),
    ]
