# Generated by Django 3.1.3 on 2021-01-02 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_auto_20210102_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentitems',
            name='renter_name',
        ),
        migrations.AddField(
            model_name='rentitems',
            name='renter_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rentitems',
            name='rented_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 21, 27, 52, 268650)),
        ),
    ]
