# Generated by Django 3.1.3 on 2021-01-05 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0007_auto_20210103_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitems',
            name='rented_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 12, 1, 56, 690055)),
        ),
    ]
