# Generated by Django 3.1.3 on 2020-11-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid_Items',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seller_email', models.EmailField(max_length=254)),
                ('threshold_value', models.FloatField()),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(default='', max_length=1000)),
                ('item_photo', models.ImageField(upload_to='Bid Item Pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Bidding_id', serialize=False, to='Bidding.bid_items')),
                ('buyer_email', models.EmailField(max_length=254)),
                ('bid_value', models.FloatField()),
                ('seller_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bidding_semail', to='Bidding.bid_items')),
                ('threshold_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bidding_threshold', to='Bidding.bid_items')),
            ],
        ),
    ]
