# Generated by Django 3.1.3 on 2020-11-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='seller_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='threshold_value',
            field=models.FloatField(),
        ),
    ]
