# Generated by Django 3.1.3 on 2020-11-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0002_auto_20201124_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='bid_value',
        ),
        migrations.AddField(
            model_name='bidding',
            name='curr_bid_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bidding',
            name='item_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='bidding',
            name='prev_bid_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='buyer_email',
            field=models.EmailField(default='-', max_length=254),
        ),
    ]
