# Generated by Django 3.1.3 on 2020-11-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0005_bid_items_item_place_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='old_items_on_bid',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seller_email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bid_Items',
            new_name='BidItems',
        ),
    ]
