# Generated by Django 3.1.3 on 2020-11-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0006_auto_20201125_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='old_items_on_bid',
            name='buyer_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='old_items_on_bid',
            name='last_bid_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='old_items_on_bid',
            name='threshold_value',
            field=models.FloatField(default=0),
        ),
    ]
