# Generated by Django 3.1.3 on 2020-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0007_auto_20201125_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='new_bid_date',
            field=models.DateField(default='2000-10-05'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='old_bid_date',
            field=models.DateField(default='2000-10-05'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='prev_buyer_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='old_items_on_bid',
            name='bid_placed_on',
            field=models.DateField(default='2000-10-05'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='threshold_value',
            field=models.FloatField(default=0),
        ),
    ]
