# Generated by Django 3.1.3 on 2020-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('Item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Item_title', models.CharField(max_length=100)),
                ('Item_ab', models.CharField(default='', max_length=100)),
                ('Item_price', models.FloatField()),
                ('Item_quantity', models.IntegerField(max_length=2)),
                ('Item_description', models.CharField(default='', max_length=1000)),
                ('Item_photo', models.ImageField(upload_to='Item_pics/')),
                ('Item_type', models.CharField(max_length=20)),
            ],
        ),
    ]
