# Generated by Django 3.1.3 on 2020-11-23 09:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Item_photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:/codes/python_codes/nirvaas_main/media'), upload_to=''),
        ),
    ]
