# Generated by Django 3.1.3 on 2020-11-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_staff', '0002_auto_20201123_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Item_photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
