# Generated by Django 3.1.3 on 2021-01-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_staff', '0003_auto_20201123_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Item_photo',
            field=models.CharField(max_length=1000),
        ),
    ]
