# Generated by Django 3.1.3 on 2020-11-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.AddField(
            model_name='cart',
            name='Order_id',
            field=models.IntegerField(default=111, primary_key=True, serialize=False),
        ),
    ]
