# Generated by Django 3.1.3 on 2020-11-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_student', '0002_auto_20201123_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='buyer_email',
        ),
        migrations.AddField(
            model_name='cart',
            name='email_id',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
