# Generated by Django 3.1.3 on 2020-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_student', '0004_auto_20201123_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.IntegerField(default=0)),
                ('Item_title', models.CharField(max_length=100)),
                ('Item_price', models.FloatField()),
                ('Item_quantity', models.IntegerField(default=1, max_length=2)),
                ('email_id', models.EmailField(default='', max_length=254)),
                ('Order_id', models.IntegerField(default=111)),
                ('Order_date', models.DateField(default='05/10/2000')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='Item_quantity',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
