# Generated by Django 3.1.3 on 2020-11-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_student', '0006_auto_20201124_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_time',
            field=models.TimeField(default='06:04'),
        ),
    ]
