# Generated by Django 3.1.3 on 2020-11-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('mobile_no', models.IntegerField(max_length=10, unique=True)),
                ('type_user', models.CharField(choices=[('Student', 'Student'), ('Stationery Staff', 'Stationery Staff'), ('Administrator', 'Administrator')], max_length=20)),
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
