# Generated by Django 3.1.3 on 2020-11-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20201120_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type_user',
            field=models.CharField(max_length=20),
        ),
    ]
