# Generated by Django 3.1.3 on 2021-01-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20201122_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('email_id', models.EmailField(max_length=50)),
                ('notification', models.CharField(max_length=100)),
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
